### ISSUE TITLE
Suggestion: switch on/off of daylight saving

### ISSUE THREAD

**Issue by ChrisFromDE** [thomasjacquin/allsky-portal#6]
Hi Thomas,
i would like to set the possibility of switching on/off the daylight saving.
I can do so by adding the Code in the daylight.sh, but with so switch this via the gui.

Is it possible?

Regards Christian

**Comment by thomasjacquin** [comment]
Sorry I missed that message.
There is currently no setting for this but it there was one, I think it would be located in config.sh because it's not really a camera setting.
Eventually, I would like to bring the config.sh to the GUI (editable text or individual settings, not sure yet). That would make things easier to configure without ussing SSH and the terminal. However I need to clean the code a little in order to do this.

**Comment by EricClaeys** [comment]
Thomas, did you ever do any work toward merging config.sh and the GUI?  If not, I'd be happy to do it.

**Comment by thomasjacquin** [comment]
@EricClaeys Since I wrote that message, I created the editor tab that lets you modify scripts manually. That was a good first step.
However, I think `config.sh` could be rendered into a better user experience. A lot of the settings are either booleans, numbers or text. It shouldn't be too difficult to create a page for these settings. I just haven't put too much thoughts into it because it touches a lot of other bash scripts and I am not sure what data representation would be best (keeping the sh file vs using a json object).
If you want to take a stab at it, please go ahead.

**Comment by EricClaeys** [comment]
Thomas,

 

I clearly don’t know what I’m doing with GitHub.

I submitted a Pull Request for a minor change to capture.cpp to check for Carriage Return in addition to Linefeed, but the PR is just sitting there.

My master branch says it is 2 commits behind yours and 27 ahead.  I would have thought it would be the same after you merged them a few days ago.  Shouldn’t it be?

 

I <think> I did a PR to allow users to specify the timelapse bitrate, but am not sure if it worked.  It also gave the message about ahead and behind.  Anyway, it updates config.sh.repro. README.md, and scripts/timelapse.sh.

 

Also, scripts/copy_notification_image.sh is not executable so people are getting errors.  How do we specify that it should be executable?  I didn’t see anything in GitHub.

 

Thanks - Eric

**Comment by thomasjacquin** [comment]
Hi Eric, Once you've submitted a PR and it's been merged, you should do a `git fetch` to retrieve the latest changes from the repo then `git checkout master` to get on the master branch, `git pull` to pull the most recent changes of that branch.

Then you can start modifying code and submit new PRs.
I'll try to fix the script permission. It's probably just a matter of `chmod +x` and then submit that change. I don't think you can change it on gitHub itself.

**Comment by EricClaeys** [comment]
Thomas,

Where do I do those commands?  From the Pi command prompt?  I don’t see any way of doing those from the GitHub web site.

I already modified some files which may be causing problems.

 

Eric

**Comment by thomasjacquin** [comment]
Yes, you type these commands in the terminal from the `allsky` directory.
If you've already made changes, `git stash` will put them aside. `git stash pop` will bring them back.

**Comment by EricClaeys** [comment]
I did those commands but on the "Eric Claeys / allsky" web page I still get the message: "This branch is 28 commits ahead, 3 commits behind thomasjacquin:master."  If I click on "Fetch upstream" it says I'm 3 commits behind and there are conflicts that need to be resolved, and I need to do a Pull Request to fetch upstream.

**Comment by EricClaeys** [comment]
Closing - original question was answered.

**Comment by bbillp** [comment]
I am of the opinion only a few folks should be making changes to the allsky programs otherwise its going to get very messy and hard for everyday users to solve problems and enjoy the software.    Bill Prats

**Comment by EricClaeys** [comment]
Bill,
Right now it's pretty much just Chris and me with Thomas doing all the merges.
Chris suggested to one person that they do a PR for a suggestion they have but last I checked they hadn't.

Eric
________________________________

**Comment by EricClaeys** [comment]
Michael Kidd recently started contributing again.
